### ISSUE TITLE
[결과 출력] 게임 다시 시작하는 케이스

### ISSUE THREAD

**Issue by minwook-shin** [kmu-system-newest-tech-23-team-b/final-project#11]
# 설명

게임 다시 시작할 때 상대방 클라이언트에서 게임 시간, 점수, 플레이어 좌표가 이전 결과를 가져오는 버그

관련 이슈 : https://github.com/kmu-system-newest-tech-23-team-b/final-project/issues/4
관련 코드 : https://github.com/kmu-system-newest-tech-23-team-b/final-project/tree/feature/game_result

# 재현 방식

1. 멀티플레이 진행
2. ESC 눌러서 게임 오버 발생
3. A 클라이언트에서 리플레이 클릭
4. A 클라이언트에서 바로 스페이스 바 눌러서 게임 시작
5. B 클라이언트 게임 데이터 오류 발생

# 스크린샷

<img width="1277" alt="스크린샷 2023-04-27 오전 10 49 35" src="https://user-images.githubusercontent.com/12551635/234740735-6e546509-4c3b-4ee1-91d3-c009ea2e8bca.png">

재현 방식의 B 클라이언트에서 게임 시간, 게임 점수, 플레이어 위치가 직전 게임 결과에서 이어지고 있습니다.

**Comment by ISCMSHY** [comment]
해당 버그 수정해서 다시 push 했습니다.!!
