### ISSUE TITLE
ggrs library에서 Remote Player의 PlayerType 구조에서 PeerId를 파싱하는 법을 잘 모르겠습니다...

### ISSUE THREAD

**Issue by ISCMSHY** [kmu-system-newest-tech-23-team-b/final-project#14]
소켓 통신에서 PeerId를 사용하여 통신하는 것을 확인했고 PeerId 값도 println문으로 확인했는데 해당 Id 값을 parsing 하는 코드를 못 짜겠습니다... PlayerType<PeerId>로 player 변수가 정의되어 있고 PlayerType이 어떻게 구조되어 있는지도 대략 확인이 되는데 어떤 함수를 통해서 parsing 해야 하는지 감이 안잡힘니다...

[print문으로 확인한 PeerId]
(코드)
![image](https://user-images.githubusercontent.com/61531215/235054125-310fd59b-3e89-4c35-88bd-d5c2dda00230.png)
(출력화면)
![image](https://user-images.githubusercontent.com/61531215/235053557-72691d36-dfcf-4b90-9d57-8eb75c045972.png)

(PlayerType 구조)
![image](https://user-images.githubusercontent.com/61531215/235054220-566df519-d586-4549-8f59-319b6d2c1f5b.png)

**Comment by minwook-shin** [comment]
@ISCMSHY 
player 의 열거형에 있는 Remote의 값을 조회하려면 패턴 매칭을 통해 값을 추출해야 합니다.
그리고 떨궈지는 필드에 접근하면 순수 peer_id 값만 얻을 수 있습니다.
아래는 예제 코드입니다.
```rust
match player {
    PlayerType::Remote(peer_id) => {
        println!("{}", peer_id.0);
    }
    _ => {}
}
```
