### ISSUE TITLE
[판정 구현] 플레이어끼리의 충돌 판정 중 플레이어 A와 플레이어 B 구분하기의 아이디어가 필요합니다

### ISSUE THREAD

**Issue by wsb8618** [kmu-system-newest-tech-23-team-b/final-project#15]
![image](https://user-images.githubusercontent.com/55951156/235093437-7303a010-8071-4bc1-a6c1-8ebf7bd18a52.png)

현재 플레이어와 플레이어끼리 충돌을 감지하는 player_hit_player 함수를 만들고 있는데 플레이어끼리의 거리를 계산해야 할 것 같습니다. 그러기 위해서는 클라이언트에서 조종중인 플레이어 A, 다른 클라이언트에서 플레이하고 있는 플레이어 B의 오브젝트를 구별해야할 것 같은데 그러기 위해서는 Player의 handle을 이용해서 구별을 해야할 것 같습니다. 어떻게 handle을 사용하여 플레이어끼리의 거리를 계산할지 감이 잡히지 않습니다.

**Comment by minwook-shin** [comment]
@wsb8618 플레이어의 구별은 카메라 함수를 참고하시면 좋을 듯 합니다.
```rust
pub fn follow(player: Option<Res<LocalPlayer>>, query: Query<(&Player, &Transform)>,
              mut camera: Query<&mut Transform, (With<Camera>, Without<Player>)>, ) {
    let is_handle = match player {
        Some(handle) => handle.0,
        None => return
    };
    for (player, player_transform) in query.iter() {
        if player.handle != is_handle { continue; }
        let pos = player_transform.translation;
        for mut transform in camera.iter_mut() {
            transform.translation.x = pos.x;
            transform.translation.y = pos.y;
        }
    }
}
```
자신의 player.handle 을 찾아서 타인의 거리를 비교해서 distance < 1.0 조건을 걸면 어떨까요?

**Comment by minwook-shin** [comment]
만약 플레이어 간의 충돌이 구현 어려우시면, 먼저 적 충돌 시 게임오버 기능 합치고 추가 개발하시는 것도 방법일 수 있습니다.

**Comment by wsb8618** [comment]
![image](https://user-images.githubusercontent.com/55951156/235115748-bec2e8f2-ffa2-46c1-b0ff-69f31b2b5f03.png)

@minwook-shin 이런식으로 is_handle이 아니면 other_pos로, is_handle이면 my_pos로 포지션을 저장하여 my_pos와 other_pos의 거리를 구하려고 하였는데 아래와 같은 에러가 나타납니다. 다른 방법이나 해결 방법이 있을까요?

**Comment by wsb8618** [comment]
@minwook-shin 클라이언트의 플레이어는 LocalPlayer로 가져올 수 있는데 다른 클라이언트의 다른 플레이어의 위치를 가져오는 법을 모르겠습니다.. 도저히 아이디어가 나오지 않네요

**Comment by minwook-shin** [comment]
@wsb8618 그러면 적 충돌만 구현하고 플레이어의 충돌은 미구현으로 넘어가야 될거같아요.
저희가 토요일부터는 코드 합치는데 집중해야 될 듯 싶어서요.
