### ISSUE TITLE
ggrs 소켓 통신 구현 과정 중 String 데이터 전달 구현에서 이해가 안되는 부분이 있습니다...

### ISSUE THREAD

**Issue by ISCMSHY** [kmu-system-newest-tech-23-team-b/final-project#17]
**"최종 목표는 String 데이터를 소켓 통신으로 주고 받을 수 있도록 구성하는 것입니다"**
아래 내용은 제가 구현해보면서 시도했던 내용입니다.

현재 ggrs 소켓 통신이 input 함수로 동작되고 있고 input 함수는 u8 데이터 밖에 전송이 안되는 걸로 확인됩니다...
u8 데이터 말고 String 데이터를 소켓 통신으로 전송하고 싶은데 여러가지 방법을 시도해도 문법적 오류가 발생합니다.

제가 이해하고 있는 구조는 ggrs::Config에서 정의된 input, state, addresss가 데이터를 담는 변수들이고 input 함수를 통해 ggrs:Config의 input 변수에 데이터가 담겨 전송되는걸로 이해하고 있습니다.

[ggrs::Config]
![image](https://user-images.githubusercontent.com/61531215/235192111-a4f36fae-f6f3-4995-b943-58614c661204.png)

[input 함수]
![image](https://user-images.githubusercontent.com/61531215/235192228-30b33c9b-9cf5-486e-8b82-53f6fd28a9c9.png)

여기서 u8말고 String으로 데이터를 전달하고 싶어서 ggrs::Config의 State를 String으로 전환 후 input 함수와 유사하게 작성한 뒤 main 함수에 아래와 같이 코드를 추가 했는데 에러가 발생합니다...

[ggrs::Config 변경]
![image](https://user-images.githubusercontent.com/61531215/235194845-c132a964-c31d-48e3-baf6-4594e20ec0ec.png)

[새로 정의한 state]
![image](https://user-images.githubusercontent.com/61531215/235193106-1a313b4c-fa98-495d-acba-05b88f4551c9.png)

[main에서의 에러]
![image](https://user-images.githubusercontent.com/61531215/235193010-3937c8be-1fc0-4234-af11-33da8c4e0d7b.png)

그래서 state말고 ggrs::Config의 input을 String으로 변경해볼려고 했지만, ggrs::Config의 input에 pod 데이터 타입이 포함되어 있어서 String으로 선언이 안됩니다...

[pod 관련 에러]
![image](https://user-images.githubusercontent.com/61531215/235193836-6fdd686a-c28a-4956-b99c-12099045aa62.png)

제가 이해하고 있는 구조가 맞는지 그리고 어떻게 구성해야 String 소켓 통신이 가능한지 궁금합니다.

**Comment by minwook-shin** [comment]
@ISCMSHY 음... packet 만들어서 소켓으로 보내고 socket.receive() 받는 방식이 있긴 합니다.

```rust
let packet = "hello world".as_bytes().to_vec().into_boxed_slice();
socket.send(packet, peer_id);
```

왜 보내시는지 모르겠지만, 만약 접속자 모두의 피어 아이디를 얻는건 아래처럼 해결할 수 있어보입니다.

이미 remote() 로 가져온 게 상대방 피어 아이디이므로  자신의 피어 아이디를 조회만 하면 될 거 같아요.
```rust
socket.id().unwrap().0
```
이렇게 소켓 불러와서 옵션 제거하면 순수하게 자신의 피어 아이디만 나옵니다.

아래처럼 완성 코드를 사용할 수 있겠네요.

```rust
match player {
    PlayerType::Remote(peer_id) => {
        println!("Remote:{}", peer_id.0);
    }
    PlayerType::Local => {
        println!("Local:{}", socket.id().unwrap().0);
    }
    _ => {}
}
```

**Comment by minwook-shin** [comment]
참고로 gars config는 아래 코드로 이루어져 있어서, 추가 및 변경은 힘듭니다.
```rust
#[cfg(feature = "sync-send")]
pub trait Config: 'static + Send + Sync {
    /// The input type for a session. This is the only game-related data
    /// transmitted over the network.
    ///
    /// Reminder: Types implementing [Pod] may not have the same byte representation
    /// on platforms with different endianness. GGRS assumes that all players are
    /// running with the same endianness when encoding and decoding inputs.
    ///
    /// [Pod]: bytemuck::Pod
    type Input: Copy + Clone + PartialEq + bytemuck::Pod + bytemuck::Zeroable + Send + Sync;

    /// The save state type for the session.
    type State: Clone + Send + Sync;

    /// The address type which identifies the remote clients
    type Address: Clone + PartialEq + Eq + Hash + Send + Sync + Debug;
}
```
