### ISSUE TITLE
장애물이 무한으로 증식하는 현상이 있습니다.

### ISSUE THREAD

**Issue by Winjae** [kmu-system-newest-tech-23-team-b/final-project#18]
![image](https://user-images.githubusercontent.com/55117741/235300015-70623d2e-96d3-4136-aad5-3a013312792d.png)
![image](https://user-images.githubusercontent.com/55117741/235300018-889a7b18-c7b9-4619-96b0-d2c1ff38fe65.png)

.add_system()에 spawn_enemy를 하나밖에 안넣었는데 장애물이 무한으로 증식하는 현상이 있습니다. spawn_enemy에는 1개의 Enemy만 생성하는 코드밖에 없는데 어떤 게 원인인지 잘 모르겠습니다.

**Comment by minwook-shin** [comment]
코드에 spawn 만 있고 despawn 과정이 없네요.
만약 장애물이 늘어나는 코드면 시간이 지나면서 순차적으로 오래된 장애물 제거도 해줘야 할 것으로 보여집니다.

**Comment by minwook-shin** [comment]
그리고... 시스템 등록하실 때 .in_schedule(OnEnter) 로 교체해보세요.
저거 사용하는 방법에 따라서 함수를 계속 수행할 수도 있습니다.

**Comment by Winjae** [comment]
감사합니다. 장애물이 무한으로 증식하는 현상은 해결했습니다. despawn과정은 위 사진에는 없지만 spawn 밑에 구현이 되어있습니다!
